ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: cluster-letsencrypt-prod
  hosts:
    - host: staging.gnarloq.games
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: gnarloq-staging-tls
      hosts:
        - staging.gnarloq.games